<?php

namespace AppBundle\Repository;

/**
 * CategoriaIngredienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaIngredienteRepository extends \Doctrine\ORM\EntityRepository
{
}
