<?php

namespace AppBundle\Repository;

/**
 * CategoriaRecetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRecetaRepository extends \Doctrine\ORM\EntityRepository
{
}
