<?php

namespace AppBundle\Repository;

/**
 * EnfermedadAlimenticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfermedadAlimenticiaRepository extends \Doctrine\ORM\EntityRepository
{
}
