<?php

namespace AppBundle\Repository;

/**
 * InformacionNutricionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformacionNutricionalRepository extends \Doctrine\ORM\EntityRepository
{
}
