<?php

namespace AppBundle\Repository;

/**
 * ItemRecetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRecetaRepository extends \Doctrine\ORM\EntityRepository
{
}
