<?php

namespace AppBundle\Repository;

/**
 * PasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasoRepository extends \Doctrine\ORM\EntityRepository
{
}
