<?php

namespace AppBundle\Repository;

/**
 * PuntuacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntuacionRepository extends \Doctrine\ORM\EntityRepository
{
}
